language: elixir
elixir:
  - 1.2
  - 1.3
  - 1.4
otp_release:
  - 18.3
  - 19.2
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/67f8d9bf9221d07f40cf
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
before_script:
  - MIX_ENV=test mix do deps.get
script:
  - mix test
after_success:
  - MIX_ENV=test mix coveralls.travis
